sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project pos-project-272409
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials pos-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
script:
  - docker build -t toanthanh/pos-client:latest -t toanthanh/pos-client:$SHA -f ./client/Dockerfile ./client
  - docker build -t toanthanh/pos-backend:latest -t toanthanh/pos-backend:$SHA -f ./backend/Dockerfile ./backend
  - docker push toanthanh/pos-client:latest
  - docker push toanthanh/pos-backend:latest
  - docker push toanthanh/pos-client:$SHA
  - docker push toanthanh/pos-backend:$SHA
  - kubectl apply -f k8s
  - kubectl set image deployments/server-deployment server=toanthanh/pos-backend:$SHA
  - kubectl set image deployments/client-deployment client=toanthanh/pos-client:$SHA
