apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: toanthanh/pos-client:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              value: mongodb://test:QwertyuioP1@ds361488.mlab.com:61488/pos
